"use client";

import { useState } from "react";
import type { SessionSummaryData, SummaryMessage } from "@/types/voice";
import { addVocabTerms } from "@/lib/vocab";
import VoiceButton from "./VoiceButton";

interface SessionSummaryProps {
  summary: SessionSummaryData;
  transcript: SummaryMessage[];
  learnerName?: string;
  subject?: string;
  onStartAnother: () => void;
  onLearnSomethingElse: () => void;
}

/** Post-session summary shown after the user ends a learning session. */
export default function SessionSummary({
  summary,
  transcript,
  learnerName,
  subject,
  onStartAnother,
  onLearnSomethingElse,
}: SessionSummaryProps) {
  const [revealed, setRevealed] = useState<Record<number, boolean>>({});
  const [savedTerms, setSavedTerms] = useState(false);
  const [copiedReport, setCopiedReport] = useState(false);

  const downloadTranscript = () => {
    const lines = [
      `KT — Learning session transcript`,
      `Learner: ${learnerName ?? "Guest"}`,
      `Topic: ${summary.topic}`,
      subject ? `Subject: ${subject}` : "",
      "",
      ...transcript.map((m) => `${m.speaker === "user" ? "You" : "KT"}: ${m.text}`),
    ];
    const blob = new Blob([lines.filter((l) => l !== "").join("\n")], {
      type: "text/plain;charset=utf-8",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `kt-session-${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const parentReport = () =>
    [
      `KT Learning Report — ${new Date().toLocaleDateString()}`,
      `Learner: ${learnerName ?? "Guest"}`,
      subject ? `Subject: ${subject}` : `Topic: ${summary.topic}`,
      ``,
      `What was covered:`,
      ...summary.learned.map((l) => `  • ${l}`),
      summary.key_terms?.length ? `\nKey terms: ${summary.key_terms.join(", ")}` : "",
      summary.exercise ? `\nPractice suggestion: ${summary.exercise}` : "",
      `\nGenerated by KT ("Learn by talking")`,
    ]
      .filter(Boolean)
      .join("\n");

  const copyReport = async () => {
    try {
      await navigator.clipboard.writeText(parentReport());
      setCopiedReport(true);
      window.setTimeout(() => setCopiedReport(false), 2000);
    } catch {
      /* clipboard unavailable */
    }
  };

  const saveKeyTerms = () => {
    addVocabTerms(summary.key_terms ?? [], `From: ${summary.topic}`);
    setSavedTerms(true);
  };

  return (
    <div className="mx-auto w-full max-w-md rounded-3xl border border-white/10 bg-white/5 p-6 sm:p-8 text-center">
      <h2 className="text-2xl font-bold text-white">Session Complete</h2>
      <p className="mt-2 text-slate-400">
        Great work{learnerName ? `, ${learnerName}` : ""} — here&apos;s what we covered.
      </p>

      <div className="mt-6 rounded-2xl bg-white/5 p-4 text-left">
        <p className="text-xs font-semibold uppercase tracking-wide text-violet-300">Topic</p>
        <p className="mt-1 text-lg font-semibold text-white">{summary.topic}</p>

        <p className="mt-4 text-xs font-semibold uppercase tracking-wide text-sky-300">What you learned</p>
        <ul className="mt-2 space-y-2">
          {summary.learned.length > 0 ? (
            summary.learned.map((item, i) => (
              <li key={i} className="flex items-start gap-2 text-slate-200">
                <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-gradient-to-r from-violet-400 to-sky-400" />
                {item}
              </li>
            ))
          ) : (
            <li className="text-slate-400">A short learning session.</li>
          )}
        </ul>

        {summary.key_terms && summary.key_terms.length > 0 && (
          <>
            <p className="mt-4 text-xs font-semibold uppercase tracking-wide text-emerald-300">Key terms</p>
            <div className="mt-2 flex flex-wrap gap-2">
              {summary.key_terms.map((term) => (
                <span key={term} className="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-sm text-slate-200">
                  {term}
                </span>
              ))}
            </div>
            <button
              type="button"
              onClick={saveKeyTerms}
              disabled={savedTerms}
              className="mt-3 rounded-full border border-emerald-400/30 bg-emerald-500/10 px-4 py-1.5 text-xs font-medium text-emerald-200 hover:bg-emerald-500/20 disabled:opacity-50 focus:outline-none focus-visible:ring-2 focus-visible:ring-emerald-300"
            >
              {savedTerms ? "✓ Saved to vocabulary notebook" : "＋ Save to vocabulary notebook"}
            </button>
          </>
        )}

        {summary.quiz && summary.quiz.length > 0 && (
          <>
            <p className="mt-4 text-xs font-semibold uppercase tracking-wide text-amber-300">Quick quiz</p>
            <ol className="mt-2 space-y-3">
              {summary.quiz.map((q, i) => (
                <li key={i} className="text-sm text-slate-200">
                  <p>{i + 1}. {q.question}</p>
                  {revealed[i] ? (
                    <p className="mt-1 rounded-lg bg-emerald-500/10 px-3 py-1.5 text-emerald-200">{q.answer}</p>
                  ) : (
                    <button
                      type="button"
                      onClick={() => setRevealed((r) => ({ ...r, [i]: true }))}
                      className="mt-1 text-xs font-medium text-amber-300 hover:text-amber-200 focus:outline-none focus-visible:ring-2 focus-visible:ring-amber-300"
                    >
                      Show answer
                    </button>
                  )}
                </li>
              ))}
            </ol>
          </>
        )}

        {summary.exercise && (
          <>
            <p className="mt-4 text-xs font-semibold uppercase tracking-wide text-sky-300">Try this at home</p>
            <p className="mt-1 text-sm text-slate-200">{summary.exercise}</p>
          </>
        )}
      </div>

      <div className="mt-5 flex flex-wrap justify-center gap-2">
        <button
          type="button"
          onClick={downloadTranscript}
          className="rounded-full border border-white/15 bg-white/5 px-4 py-2 text-xs font-medium text-slate-300 hover:bg-white/10 hover:text-white focus:outline-none focus-visible:ring-2 focus-visible:ring-sky-300"
        >
          ⬇ Download transcript
        </button>
        <button
          type="button"
          onClick={copyReport}
          className="rounded-full border border-white/15 bg-white/5 px-4 py-2 text-xs font-medium text-slate-300 hover:bg-white/10 hover:text-white focus:outline-none focus-visible:ring-2 focus-visible:ring-sky-300"
        >
          {copiedReport ? "✓ Report copied" : "📋 Copy report (for parents)"}
        </button>
      </div>

      <div className="mt-6 flex flex-col gap-3 sm:flex-row sm:justify-center">
        <VoiceButton label="🎙 Start Another Session" onClick={onStartAnother} />
        <VoiceButton label="Learn Something Else" onClick={onLearnSomethingElse} variant="secondary" />
      </div>
    </div>
  );
}
